---
kind: Deployment
apiVersion: v1
metadata:
  name: @project.artifactId@
  namespace: learning-platform
  labels:
    app: @project.artifactId@
spec:
  replicas: 2
  selector:
    matchLabels:
      app: @project.artifactId@
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: @project.artifactId@
    spec:
      initContainers:
        - name: fix-permissions
          image: "alpine"
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /var/www/html/upload
              name: pvc
              subPath: limesurvey-upload
            - mountPath: /var/www/html/plugins
              name: pvc
              subPath: limesurvey-plugins
            - mountPath: /var/www/html/tmp/assets
              name: pvc
              subPath: limesurvey-tmp-assets
          command:
            - sh
            - -c
            - (chmod 770 -R /var/www/html/upload; chown 33:33 /var/www/html/upload; chmod 770 -R /var/www/html/plugins; chown -R 33:33 /var/www/html/plugins; chmod 770 /var/www/html/tmp/assets; chown -R 33:33 /var/www/html/tmp/assets)
      containers:
        - name: @project.artifactId@
          image: @project.groupId@/@project.artifactId@:@project.version@
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-user
                  key: database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-user
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-user
                  key: password
            - name: DB_TABLE_PREFIX
              value: limesurvey_
            - name: DBENGINE
              value: MyISAM
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: ADMIN_USER
              value: admin
            - name: ADMIN_PASSWORD
              value: password
            - name: ADMIN_NAME
              value: Lime Administrator
            - name: PUBLIC_URL
              value: "https://{{ public_host_with_port }}/limesurvey"
            - name: BASE_URL
              value: "/limesurvey"
            - name: HOST_INFO
              value: "https://{{ public_host_with_port }}"
          volumeMounts:
            - mountPath: /var/www/html/upload
              name: pvc
              subPath: limesurvey-upload
            - mountPath: /var/www/html/plugins
              name: pvc
              subPath: limesurvey-plugins
            - mountPath: /var/www/html/tmp/assets
              name: pvc
              subPath: limesurvey-tmp-assets
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              memory: 512Mi
              cpu: 150m
            limits:
              memory: 1024Mi
              cpu: 500m
          startupProbe:
            tcpSocket:
              port: http
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: @project.artifactId@