---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: @project.artifactId@
  namespace: learning-platform
  annotations:
    kubernetes.io/ingress.class: public
spec:
  rules:
   -  host: limesurvey.{{ public_host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: @project.artifactId@
                port:
                  number: 8080