---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: @project.artifactId@
  namespace: learning-platform
  annotations:
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
        - {{ public_host }}
      secretName: tls-secret
  rules:
   -  host: {{ public_host }}
      http:
        paths:
          - path: /limesurvey(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: @project.artifactId@
                port:
                  number: 8080