---
kind: Deployment
apiVersion: v1
metadata:
  name: @project.artifactId@
  namespace: learning-platform
  labels:
    app: @project.artifactId@
spec:
  replicas: 1
  selector:
    matchLabels:
      app: @project.artifactId@
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: @project.artifactId@
    spec:
      containers:
        - name: @project.artifactId@
          image: @project.groupId@/@project.artifactId@:@project.version@
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-user
                  key: database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-user
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-user
                  key: password
            - name: DB_TABLE_PREFIX
              value: limesurvey_
            - name: DBENGINE
              value: MyISAM
            - name: ADMIN_USER
              value: admin
            - name: ADMIN_PASSWORD
              value: password
            - name: ADMIN_NAME
              value: Lime Administrator
            - name: PUBLIC_URL
              value: "http://limesurvey.{{ public_host }}"
          volumeMounts:
            - mountPath: /var/www/html/upload
              name: pvc
              subPath: limesurvey-upload
            - mountPath: /var/www/html/plugins
              name: pvc
              subPath: limesurvey-plugins
            #- mountPath: /var/www/html/application/config
            #  name: pvc
            #  subPath: limesurvey-config
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              memory: 512Mi
              cpu: 150m
            limits:
              memory: 1024Mi
              cpu: 500m
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 5
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: @project.artifactId@