---
apiVersion: v1
kind: Secret
metadata:
  name: @project.artifactId@-admin
  namespace: survey-platform
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: {{ lookup('ansible.builtin.password', '/dev/null', chars=['hexdigits'], length=30) }}