---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: @project.artifactId@
  namespace: learning-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi