---
kind: Deployment
apiVersion: v1
metadata:
  name: @project.artifactId@
  namespace: learning-platform
  labels:
    app: @project.artifactId@
spec:
  replicas: 1
  selector:
    matchLabels:
      app: @project.artifactId@
  template:
    metadata:
      labels:
        app: @project.artifactId@
    spec:
      containers:
        - name: @project.artifactId@
          image: @project.groupId@/@project.artifactId@:@project.version@
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-user
                  key: database
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-user
                  key: username
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-user
                  key: password
            - name: WORDPRESS_TABLE_PREFIX
              value: "wordpress_"
            - name: WORDPRESS_CONFIG_EXTRA
              value: >-
                define('WP_HOME', 'https://{{ public_host_with_port }}/');
                define('WP_SITEURL', 'https://{{ public_host_with_port }}/');
          volumeMounts:
            - mountPath: /var/www/html
              name: pvc
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              memory: 512Mi
              cpu: 150m
            limits:
              memory: 1024Mi
              cpu: 500m
          startupProbe:
            httpGet:
              path: /
              port: 80
              httpHeaders:
                - name: X-Forwarded-Proto
                  value: http
                - name: X-Forwarded-Host
                  value: "{{ public_host }}"
                - name: Host
                  value: "{{ public_host }}"
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
              httpHeaders:
                - name: X-Forwarded-Proto
                  value: http
                - name: X-Forwarded-Host
                  value: "{{ public_host }}"
                - name: Host
                  value: "{{ public_host }}"
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
              httpHeaders:
                - name: X-Forwarded-Proto
                  value: http
                - name: X-Forwarded-Host
                  value: "{{ public_host }}"
                - name: Host
                  value: "{{ public_host }}"
            periodSeconds: 5
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: @project.artifactId@