---
kind: Deployment
apiVersion: v1
metadata:
  name: @project.artifactId@
  namespace: paks
  labels:
    app: @project.artifactId@
spec:
  replicas: 1
  selector:
    matchLabels:
      app: @project.artifactId@
  template:
    metadata:
      labels:
        app: @project.artifactId@
    spec:
      containers:
        - name: @project.artifactId@
          image: @project.groupId@/@project.artifactId@:@project.version@
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: password
            - name: WORDPRESS_CONFIG_EXTRA
              value: admin
          volumeMounts:
            - mountPath: /var/www/html
              name: pvc
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              memory: 512Mi
              cpu: 150m
            limits:
              memory: 1024Mi
              cpu: 500m
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: @project.artifactId@