---
kind: Deployment
apiVersion: v1
metadata:
  name: @project.artifactId@
  namespace: survey-platform
  labels:
    app: @project.artifactId@
spec:
  replicas: 2
  selector:
    matchLabels:
      app: @project.artifactId@
  template:
    metadata:
      labels:
        app: @project.artifactId@
    spec:
      containers:
        - name: @project.artifactId@
          image: @project.groupId@/@project.artifactId@:@project.version@
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-user
                  key: database
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-user
                  key: username
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-user
                  key: password
            - name: WORDPRESS_TABLE_PREFIX
              value: "wordpress_"
            - name: WORDPRESS_CONFIG_EXTRA
              value: >-
                define('WP_HOME', '{{ public_url }}/');
                define('WP_SITEURL', '{{ public_url }}/');
          volumeMounts:
            - mountPath: /var/www/html
              name: pvc
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              memory: 400Mi
              cpu: 250m
            limits:
              memory: 1000Mi
              cpu: 1500m
          startupProbe:
            tcpSocket:
              port: http
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: @project.artifactId@