---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: @project.artifactId@
  namespace: survey-platform
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi