---
apiVersion: v1
kind: Secret
metadata:
  name: @project.artifactId@
  namespace: learning-platform
type: kubernetes.io/basic-auth
stringData:
  password: {{ lookup('ansible.builtin.password', '/dev/null', chars=['hexdigits'], length=30) }}