---
apiVersion: v1
kind: Secret
metadata:
  name: @project.artifactId@-user
  namespace: learning-platform
type: kubernetes.io/basic-auth
stringData:
  database: learning_platform
  username: learning_platform
  password: {{ lookup('ansible.builtin.password', '/dev/null', chars=['hexdigits'], length=30) }}