---
apiVersion: v1
kind: Secret
metadata:
  name: @project.artifactId@-root
  namespace: learning-platform
type: kubernetes.io/basic-auth
stringData:
  username: root
  password: {{ lookup('ansible.builtin.password', '/dev/null', chars=['hexdigits'], length=30) }}