---
- name: Deploy server playbook
  hosts: all
  vars_prompt:
    - name: public_host
      prompt: "Host name? Example: learningplatform.com"
      private: no
    - name: public_url
      prompt: "Scheme, Host name and port (if used)? Examples: \"https://learningplatform.com\", \"https://learningplatform.com:7443\""
      private: no
    - name: clean
      prompt: Clean deploy?
      private: no
      default: no
    - name: tls
      prompt: "Configure TLS? Note: tls.key and tls.crt files must be present at roles/k8s-setup/files directory"
      private: no
      default: no
    - name: root_deployment_directory
      prompt: Enter root deployment_directory
      private: no
      default: kubernetes
    - name: apps
      prompt: Enter apps to deploy
      private: no
      default: mysql, limesurvey, redis, wordpress
  tasks:
    - name: Install microk8s
      include_role:
        name: microk8s
    - name: Ansible k8s plugin setup
      include_role:
        name: ansible-k8s-plugin
      when:
        - clean is defined
        - clean | bool
    - name: Setup for k8s
      include_role:
        name: k8s-setup
    - name: Deploy k8s component
      include_role:
        name: k8s-deployment
      vars:
        deployment_directory: "{{ root_deployment_directory + '/' + item }}"
      loop: "{{ apps.split(',') | map('trim') | list }}"
      loop_control:
        label: "{{ item }}"
    - name: Post setup for k8s
      include_role:
        name: k8s-post-setup